package com.gmail.magpro116.flags;

import android.content.Context;
import android.graphics.Bitmap;
import android.widget.Spinner;

public class MagPro {

    Context context;
    Spinner spinner;

    public MagPro(Context context, Spinner spinner) {
        this.context = context;
        this.spinner = spinner;
    }


    public void fillSpinner() {
        SpinnerAdapter adapter = new SpinnerAdapter(context, flags(), codes(), names(context));
        spinner.setAdapter(adapter);
    }

    public String getCode() {
        SpinnerAdapter adapter = new SpinnerAdapter(context, flags(), codes(), names(context));
        return adapter.returnCodes(spinner.getSelectedItemPosition());
    }

    public String getName() {
        SpinnerAdapter adapter = new SpinnerAdapter(context, flags(), codes(), names(context));
        return adapter.returnName(spinner.getSelectedItemPosition());
    }

    public Bitmap getFlag() {
        SpinnerAdapter adapter = new SpinnerAdapter(context, flags(), codes(), names(context));
        if (spinner.getSelectedItemPosition() !=0){
            return adapter.returnFlag(spinner.getSelectedItemPosition());
        }else {
            return null;
        }
    }



    public Integer[] flags(){
        Integer[] mFlags = new Integer[]{
                R.drawable.afghanistan, R.drawable.albania,
                R.drawable.algeria, R.drawable.andorra,
                R.drawable.angola, R.drawable.antigua_and_barbuda,
                R.drawable.argentina, R.drawable.armenia,
                R.drawable.australia, R.drawable.austria,
                R.drawable.azerbaijan, R.drawable.bahamas,
                R.drawable.bahrain, R.drawable.bangladesh,
                R.drawable.barbados, R.drawable.belarus,
                R.drawable.belgium, R.drawable.belize,
                R.drawable.benien, R.drawable.bhutan,
                R.drawable.bolivia, R.drawable.bosnia_and_herzegovina,
                R.drawable.botswana, R.drawable.brazil,
                R.drawable.brunei, R.drawable.bulgaria,
                R.drawable.borkinan_faso, R.drawable.borondy,
                R.drawable.cambodia, R.drawable.cameron,
                R.drawable.canada, R.drawable.cape_vedri,
                R.drawable.center_africa, R.drawable.chad,
                R.drawable.chile, R.drawable.china_republic,
                R.drawable.colombia, R.drawable.qamar,
                R.drawable.congho, R.drawable.costa_rica,
                R.drawable.cote_de_voar, R.drawable.croatia,
                R.drawable.cuba, R.drawable.cyprus,
                R.drawable.czech_republic, R.drawable.denmark,
                R.drawable.jebouty, R.drawable.dominica,
                R.drawable.dominican, R.drawable.east_timor,
                R.drawable.ecuador, R.drawable.egypt,
                R.drawable.elsalvador, R.drawable.equatorial_guinea,
                R.drawable.eretria, R.drawable.estonia,
                R.drawable.ethuobia, R.drawable.fiji,
                R.drawable.finland, R.drawable.france,
                R.drawable.gaboun, R.drawable.gambia,
                R.drawable.georgia, R.drawable.germany,
                R.drawable.ghana, R.drawable.greece,
                R.drawable.grenada, R.drawable.guatemala,
                R.drawable.papua_new_guinea, R.drawable.guinea_bissau,
                R.drawable.guyana, R.drawable.haiti,
                R.drawable.honduras, R.drawable.hungary,
                R.drawable.iceland, R.drawable.india,
                R.drawable.indonesia, R.drawable.iran,
                R.drawable.iraq, R.drawable.ireland,
                R.drawable.israel, R.drawable.italy,
                R.drawable.jamaica, R.drawable.japan,
                R.drawable.jordan, R.drawable.kazakhstan,
                R.drawable.kenya, R.drawable.kiribati,
                R.drawable.north_korea, R.drawable.south_korea,
                R.drawable.kuwait, R.drawable.kyrgyzstan,
                R.drawable.laos, R.drawable.latvia,
                R.drawable.lebanon, R.drawable.lesotho,
                R.drawable.liberia, R.drawable.libya,
                R.drawable.liechtenstein, R.drawable.lithuania,
                R.drawable.luxembourg, R.drawable.macedonia,
                R.drawable.madagascar, R.drawable.malawi,
                R.drawable.malaysia, R.drawable.maldives,
                R.drawable.mali, R.drawable.malta,
                R.drawable.marshall_islands, R.drawable.mauritania,
                R.drawable.mauritius, R.drawable.mexico,
                R.drawable.federated_states_of_micronesia, R.drawable.moldova,
                R.drawable.monaco, R.drawable.mongolia,
                R.drawable.montenegro, R.drawable.morocco,
                R.drawable.mozambique, R.drawable.myanmar,
                R.drawable.namibia, R.drawable.nauru,
                R.drawable.nepal, R.drawable.netherlands,
                R.drawable.new_zealand, R.drawable.nicaragua,
                R.drawable.niger, R.drawable.nigeria,
                R.drawable.norway, R.drawable.oman,
                R.drawable.pakistan,R.drawable.palau,
                R.drawable.panama, R.drawable.papua_new_guinea,
                R.drawable.paraguay, R.drawable.peru,
                R.drawable.philippines, R.drawable.poland,
                R.drawable.portugal, R.drawable.qatar,
                R.drawable.romania,R.drawable.russia,
                R.drawable.rwanda, R.drawable.saint_kitts,
                R.drawable.saint_lucia, R.drawable.saint_vincent_and_grenadines,
                R.drawable.samoa, R.drawable.san_marino,
                R.drawable.sao_tom, R.drawable.ksa,
                R.drawable.senegal,R.drawable.serbia,
                R.drawable.seychelles, R.drawable.sierra_leone,
                R.drawable.singapore, R.drawable.slovakia,
                R.drawable.slovenia, R.drawable.solomon_islands,
                R.drawable.somalia, R.drawable.south_africa,
                R.drawable.spain, R.drawable.sri_lanka,
                R.drawable.sudan, R.drawable.suriname,
                R.drawable.swaziland, R.drawable.sweden,
                R.drawable.switzerland, R.drawable.syria,
                R.drawable.taiwan,
                R.drawable.tajikistan, R.drawable.tanzania,
                R.drawable.thailand, R.drawable.togo,
                R.drawable.tonga, R.drawable.trinidad_and_tobago,
                R.drawable.tunisia, R.drawable.turkey,
                R.drawable.turkmenistan, R.drawable.tuvalu,
                R.drawable.uganda, R.drawable.ukraine,
                R.drawable.uae, R.drawable.uk,
                R.drawable.usa, R.drawable.uruguay,
                R.drawable.uzbekistan, R.drawable.vanuatu,
                R.drawable.vatican, R.drawable.venezuela,
                R.drawable.vietnam, R.drawable.yemen,
                R.drawable.zambia, R.drawable.zimbabwe
        };
        return mFlags;
    }

    public String[] codes(){
        String[] xz = new String[]{
                "93", "355",
                "213", "376",
                "244", "1-268",
                "54", "374",
                "61", "43",
                "994", "1-242",
                "973", "880",
                "1-246", "375",
                "32", "501",
                "229", "975",
                "591", "387",
                "267", "55",
                "673", "359",
                "226", "257",
                "855", "237",
                "1", "238",
                "236", "235",
                "56", "86",
                "57", "269",
                "242", "506",
                "225", "385",
                "53", "357",
                "420", "45",
                "253", "1-767",
                "1-809", "670",
                "593", "20",
                "503", "240",
                "291", "372",
                "251", "679",
                "358", "33",
                "241", "220",
                "995", "49",
                "233", "30",
                "1-473", "502",
                "224", "245",
                "592", "509",
                "504", "36",
                "354", "91",
                "62", "98",
                "964", "353",
                "972", "39",
                "1-876", "81",
                "962", "7",
                "254", "686",
                "850", "82",
                "965", "996",
                "856", "371",
                "961", "266",
                "231", "218",
                "423", "370",
                "352", "389",
                "261", "265",
                "60", "960",
                "223", "356",
                "692", "222",
                "230", "52",
                "691", "373",
                "377", "976",
                "382", "212",
                "258", "95",
                "264", "674",
                "977", "31",
                "64", "505",
                "227", "234",
                "47", "968",
                "92", "680",
                "507", "675",
                "595", "51",
                "63", "48",
                "351", "974",
                "40", "7",
                "250", "1-869",
                "1-758", "1-784",
                "685", "378",
                "239", "966",
                "221", "381",
                "248", "232",
                "65", "421",
                "386", "677",
                "252", "27",
                "34", "94",
                "249", "597",
                "268", "46",
                "41", "963",
                "886",
                "992", "255",
                "66", "228",
                "676", "1-868",
                "216", "90",
                "993", "688",
                "256", "380",
                "971", "44",
                "1", "598",
                "998", "678",
                "379", "58",
                "84", "967",
                "260","263"
        };
        return xz;
    }

    public String[] names(Context context){
        String[] xz = new String[]{
                context.getString(R.string.Afghanistan), context.getString(R.string.Albania),
                context.getString(R.string.Algeria), context.getString(R.string.Andorra),
                context.getString(R.string.Angola), context.getString(R.string.Antigua_Barbuda),
                context.getString(R.string.Argentina), context.getString(R.string.Armenia),
                context.getString(R.string.Australia), context.getString(R.string.Austria),
                context.getString(R.string.Azerbaijan), context.getString(R.string.TheBahamas),
                context.getString(R.string.Bahrain), context.getString(R.string.Bangladesh),
                context.getString(R.string.Barbados), context.getString(R.string.Belarus),
                context.getString(R.string.Belgium), context.getString(R.string.Belize),
                context.getString(R.string.Benin), context.getString(R.string.Bhutan),
                context.getString(R.string.Bolivia), context.getString(R.string.Bosnia_Herzegovina),
                context.getString(R.string.Botswana), context.getString(R.string.Brazil),
                context.getString(R.string.Brunei), context.getString(R.string.Bulgaria),
                context.getString(R.string.BurkinaFaso), context.getString(R.string.Burundi),
                context.getString(R.string.Cambodia), context.getString(R.string.Cameroon),
                context.getString(R.string.Canada), context.getString(R.string.Cape_Verde),
                context.getString(R.string.CentralAfricanRepublic), context.getString(R.string.Chad),
                context.getString(R.string.Chile), context.getString(R.string.China),
                context.getString(R.string.Colombia), context.getString(R.string.Comoros),
                context.getString(R.string.RepublicoftheCongo), context.getString(R.string.CostaRica),
                context.getString(R.string.CoteDIvoire), context.getString(R.string.Croatia),
                context.getString(R.string.Cuba), context.getString(R.string.Cyprus),
                context.getString(R.string.CzechRepublic), context.getString(R.string.Denmark),
                context.getString(R.string.Djibouti), context.getString(R.string.Dominica),
                context.getString(R.string.DominicanRepublic), context.getString(R.string.EastTimor),
                context.getString(R.string.Ecuador), context.getString(R.string.Egypt),
                context.getString(R.string.ElSalvador), context.getString(R.string.EquatorialGuinea),
                context.getString(R.string.Eritrea), context.getString(R.string.Estonia),
                context.getString(R.string.Ethiopia), context.getString(R.string.Fiji),
                context.getString(R.string.Finland), context.getString(R.string.France),
                context.getString(R.string.Gabon), context.getString(R.string.Gambia),
                context.getString(R.string.Georgia), context.getString(R.string.Germany),
                context.getString(R.string.Ghana), context.getString(R.string.Greece),
                context.getString(R.string.Grenada), context.getString(R.string.Guatemala),
                context.getString(R.string.Guinea), context.getString(R.string.GuineaBissau),
                context.getString(R.string.Guyana), context.getString(R.string.Haiti),
                context.getString(R.string.Honduras), context.getString(R.string.Hungary),
                context.getString(R.string.Iceland), context.getString(R.string.India),
                context.getString(R.string.Indonesia), context.getString(R.string.Iran),
                context.getString(R.string.Iraq), context.getString(R.string.Ireland),
                context.getString(R.string.Israel), context.getString(R.string.Italy),
                context.getString(R.string.Jamaica), context.getString(R.string.Japan),
                context.getString(R.string.Jordan), context.getString(R.string.Kazakhstan),
                context.getString(R.string.Kenya), context.getString(R.string.Kiribati),
                context.getString(R.string.KoreaNorth), context.getString(R.string.KoreaSouth),
                context.getString(R.string.Kuwait), context.getString(R.string.Kyrgyzstan),
                context.getString(R.string.Laos), context.getString(R.string.Latvia),
                context.getString(R.string.Lebanon), context.getString(R.string.Lesotho),
                context.getString(R.string.Liberia), context.getString(R.string.Libya),
                context.getString(R.string.Liechtenstein), context.getString(R.string.Lithuania),
                context.getString(R.string.Luxembourg), context.getString(R.string.Macedonia),
                context.getString(R.string.Madagascar), context.getString(R.string.Malawi),
                context.getString(R.string.Malaysia), context.getString(R.string.Maldives),
                context.getString(R.string.Mali), context.getString(R.string.Malta),
                context.getString(R.string.MarshallIslands), context.getString(R.string.Mauritania),
                context.getString(R.string.Mauritius), context.getString(R.string.Mexico),
                context.getString(R.string.FederatedStatesofMicronesia), context.getString(R.string.Moldova),
                context.getString(R.string.Monaco), context.getString(R.string.Mongolia),
                context.getString(R.string.Montenegro), context.getString(R.string.Morocco),
                context.getString(R.string.Mozambique), context.getString(R.string.Myanmar),
                context.getString(R.string.Namibia), context.getString(R.string.Nauru),
                context.getString(R.string.Nepal), context.getString(R.string.Netherlands),
                context.getString(R.string.NewZealand), context.getString(R.string.Nicaragua),
                context.getString(R.string.Niger), context.getString(R.string.Nigeria),
                context.getString(R.string.Norway), context.getString(R.string.Oman),
                context.getString(R.string.Pakistan), context.getString(R.string.Palau),
                context.getString(R.string.Panama), context.getString(R.string.PapuaNewGuinea),
                context.getString(R.string.Paraguay), context.getString(R.string.Peru),
                context.getString(R.string.Philippines), context.getString(R.string.Poland),
                context.getString(R.string.Portugal), context.getString(R.string.Qatar),
                context.getString(R.string.Romania), context.getString(R.string.Russia),
                context.getString(R.string.Rwanda), context.getString(R.string.SaintKittsandNevis),
                context.getString(R.string.SaintLucia), context.getString(R.string.SaintVincentandtheGrenadines),
                context.getString(R.string.Samoa), context.getString(R.string.SanMarino),
                context.getString(R.string.SaoTomeandPrincipe), context.getString(R.string.ksa),
                context.getString(R.string.Senegal), context.getString(R.string.Serbia),
                context.getString(R.string.Seychelles), context.getString(R.string.SierraLeone),
                context.getString(R.string.Singapore), context.getString(R.string.Slovakia),
                context.getString(R.string.Slovenia), context.getString(R.string.SolomonIslands),
                context.getString(R.string.Somalia), context.getString(R.string.SouthAfrica),
                context.getString(R.string.Spain), context.getString(R.string.SriLanka),
                context.getString(R.string.Sudan), context.getString(R.string.Suriname),
                context.getString(R.string.Swaziland), context.getString(R.string.Sweden),
                context.getString(R.string.Switzerland), context.getString(R.string.Syria),
                context.getString(R.string.tiwan),
                context.getString(R.string.Tajikistan), context.getString(R.string.Tanzania),
                context.getString(R.string.Thailand), context.getString(R.string.Togo),
                context.getString(R.string.Tonga), context.getString(R.string.TrinidadandTobago),
                context.getString(R.string.Tunisia), context.getString(R.string.Turkey),
                context.getString(R.string.Turkmenistan), context.getString(R.string.Tuvalu),
                context.getString(R.string.Uganda), context.getString(R.string.Ukraine),
                context.getString(R.string.uae), context.getString(R.string.UnitedKingdom),
                context.getString(R.string.usa), context.getString(R.string.Uruguay),
                context.getString(R.string.Uzbekistan), context.getString(R.string.Vanuatu),
                context.getString(R.string.Vatican), context.getString(R.string.Venezuela),
                context.getString(R.string.Vietnam), context.getString(R.string.Yemen),
                context.getString(R.string.Zambia), context.getString(R.string.Zimbabwe)
        };
        return xz;
    }



}
